### ISSUE TITLE
could not open resource metadata file - no such file.

### ISSUE THREAD

**Issue by SweetsMarie** [i-kulgu/ik-illegalweapon#1]
I have not touched the manifest, ensured it after it's dependencies, debug checked it and have the lastest artifat version but it is telling me - could not open resource metadata file - no such file. You're blackmarket script whose manifest is exactly the same except for script name manifest-wise works.. I am scratching my head.
![image](https://user-images.githubusercontent.com/87447081/175202592-cb927a8c-8879-4b3a-89eb-53f287de5de8.png)

**Comment by i-kulgu** [comment]
> I have not touched the manifest, ensured it after it's dependencies, debug checked it and have the lastest artifat version but it is telling me - could not open resource metadata file - no such file. You're blackmarket script whose manifest is exactly the same except for script name manifest-wise works.. I am scratching my head. ![image](https://user-images.githubusercontent.com/87447081/175202592-cb927a8c-8879-4b3a-89eb-53f287de5de8.png)

This is because you have dropped the script into your resources folder and trying to start it without doing refresh command on your server or restarting your server. After a restart or a refresh it will work.
