### ISSUE TITLE
any help on this one 

### ISSUE THREAD

**Issue by EdwinShima** [i-kulgu/ik-illegalweapon#2]
![image](https://user-images.githubusercontent.com/85160596/182044477-80076a1e-7cbf-4c54-a94b-369947fd5ee3.png)

**Comment by i-kulgu** [comment]
> ![image](https://user-images.githubusercontent.com/85160596/182044477-80076a1e-7cbf-4c54-a94b-369947fd5ee3.png)

Your coordinates are not correct, check config file for locations and correct any wrong format.
